In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('hotel_info.csv')

In [3]:
df.head()

,business_status,geometry,icon,name_x,opening_hours,photos,place_id,plus_code,rating_x,reference,...,price_level_x,international_phone_number,name_y,rating_y,reviews,user_ratings_total_y,website,all_ratings,all_reviews,price_level_y
0,OPERATIONAL,"{'location': {'lat': 20.6939009, 'lng': -105.2...",https://maps.gstatic.com/mapfiles/place_api/ic...,casa LAS PIÑAS,{'open_now': False},"[{'height': 640, 'html_attributions': ['<a hre...",ChIJIeVYvYNGIYQRh-9bPVK3fCU,"{'compound_code': 'MPVG+H8 Jarretaderas, Nayar...",4.6,ChIJIeVYvYNGIYQRh-9bPVK3fCU,...,NaN,+52 322 102 8516,casa LAS PIÑAS,4.6,"[{'author_name': 'Jovita Garcia Fernandez', 'a...",8.0,https://www.facebook.com/departamentos.laspinas/,"[5, 5, 5, 5, 5]","['An excellent place has all the comforts', 'I...",NaN
1,OPERATIONAL,"{'location': {'lat': 20.6920731, 'lng': -105.2...",https://maps.gstatic.com/mapfiles/place_api/ic...,Villas Victoria Confort Jarretaderas,{'open_now': True},NaN,ChIJdSKPg3xHIYQRlZ0pmfgVPiQ,"{'compound_code': 'MPRG+R4 Jarretaderas, Nayar...",5.0,ChIJdSKPg3xHIYQRlZ0pmfgVPiQ,...,NaN,+52 322 297 0093,Villas Victoria Confort Jarretaderas,5.0,"[{'author_name': 'anahi chavez', 'author_url':...",1.0,https://www.villasvictoriacomfort.com/,[5],"['It was more than I expected! Cheap, spacious...",NaN
2,OPERATIONAL,"{'location': {'lat': 20.689785, 'lng': -105.27...",https://maps.gstatic.com/mapfiles/place_api/ic...,Lada telefonica,NaN,NaN,ChIJ8RLPC-VHIYQR8Bw635S5JCo,"{'compound_code': 'MPQF+W9 Las Juntas, Jalisco...",NaN,ChIJ8RLPC-VHIYQR8Bw635S5JCo,...,NaN,+57 301 4649339,Lada telefonica,NaN,NaN,NaN,NaN,[],[],NaN
3,OPERATIONAL,"{'location': {'lat': 20.6939068, 'lng': -105.2...",https://maps.gstatic.com/mapfiles/place_api/ic...,Hotel Posada Alejandra,NaN,"[{'height': 349, 'html_attributions': ['<a hre...",ChIJB2Yha4NGIYQRE-GTtF_VSAU,"{'compound_code': 'MPVF+HF Jarretaderas, Nayar...",4.0,ChIJB2Yha4NGIYQRE-GTtF_VSAU,...,NaN,+52 322 135 6145,Hotel Posada Alejandra,4.0,"[{'author_name': 'Juan Carlos Lopez', 'author_...",54.0,https://www.google.com/url?sa=t&source=web&rct...,"[3, 4, 3, 3, 5]","[""Just for one night it's alright"", 'Discreet'...",NaN
4,OPERATIONAL,"{'location': {'lat': 20.6938115, 'lng': -105.2...",https://maps.gstatic.com/mapfiles/place_api/ic...,casa LAS PIÑAS,NaN,NaN,ChIJHd0vt_1HIYQRQxgGpgI4Oi0,"{'compound_code': 'MPVG+G5 Jarretaderas, Nayar...",NaN,ChIJHd0vt_1HIYQRQxgGpgI4Oi0,...,NaN,NaN,casa LAS PIÑAS,NaN,NaN,NaN,NaN,[],[],NaN

In [4]:
df.shape

(955, 24)

In [5]:
df.describe(include='all')

,business_status,geometry,icon,name_x,opening_hours,photos,place_id,plus_code,rating_x,reference,...,price_level_x,international_phone_number,name_y,rating_y,reviews,user_ratings_total_y,website,all_ratings,all_reviews,price_level_y
count,955,955,955,955,354,683,955,952,688.000000,955,...,4.0,712,955,688.000000,688,688.000000,551,955,955,4.0
unique,1,614,5,631,2,513,646,585,NaN,646,...,NaN,412,631,NaN,442,NaN,325,214,393,NaN
top,OPERATIONAL,"{'location': {'lat': 20.65340699999999, 'lng':...",https://maps.gstatic.com/mapfiles/place_api/ic...,Hotel Tropicus,{'open_now': True},"[{'height': 2848, 'html_attributions': ['<a hr...",ChIJOVGit01FIYQRHVOE3LZx-68,"{'compound_code': 'MQ3F+9V Puerto Vallarta, Ja...",NaN,ChIJOVGit01FIYQRHVOE3LZx-68,...,NaN,+52 322 226 4000,Hotel Tropicus,NaN,"[{'author_name': 'ron jensen', 'author_url': '...",NaN,https://www.facebook.com/hotelcartagenapv/,[],[],NaN
freq,955,23,920,9,277,3,9,23,NaN,9,...,NaN,13,9,NaN,9,NaN,9,267,267,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.354797,NaN,...,2.0,NaN,NaN,4.354215,NaN,310.202035,NaN,NaN,NaN,2.0
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.561092,NaN,...,0.0,NaN,NaN,0.560785,NaN,726.443484,NaN,NaN,NaN,0.0
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,...,2.0,NaN,NaN,1.000000,NaN,1.000000,NaN,NaN,NaN,2.0
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.000000,NaN,...,2.0,NaN,NaN,4.000000,NaN,5.000000,NaN,NaN,NaN,2.0
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.400000,NaN,...,2.0,NaN,NaN,4.400000,NaN,40.000000,NaN,NaN,NaN,2.0
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.700000,NaN,...,2.0,NaN,NaN,4.700000,NaN,188.000000,NaN,NaN,NaN,2.0
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,NaN,...,2.0,NaN,NaN,5.000000,NaN,6217.000000,NaN,NaN,NaN,2.0

In [6]:
df1 = df.drop_duplicates(subset=['place_id'], inplace=False)

In [7]:
df1.shape

(646, 24)

In [8]:
df1.describe(include='all')

,business_status,geometry,icon,name_x,opening_hours,photos,place_id,plus_code,rating_x,reference,...,price_level_x,international_phone_number,name_y,rating_y,reviews,user_ratings_total_y,website,all_ratings,all_reviews,price_level_y
count,646,646,646,646,218,436,646,643,442.000000,646,...,1.0,457,646,442.000000,442,442.000000,336,646,646,1.0
unique,1,614,5,631,2,436,646,585,NaN,646,...,NaN,412,631,NaN,442,NaN,325,214,393,NaN
top,OPERATIONAL,"{'location': {'lat': 20.65340699999999, 'lng':...",https://maps.gstatic.com/mapfiles/place_api/ic...,Puerto Vallarta,{'open_now': True},"[{'height': 606, 'html_attributions': ['<a hre...",ChIJH07bwLxFIYQRwnD_-wmnVPE,"{'compound_code': 'MQ3F+9V Puerto Vallarta, Ja...",NaN,ChIJH07bwLxFIYQRwnD_-wmnVPE,...,NaN,+52 322 226 4000,Puerto Vallarta,NaN,"[{'author_name': 'Enrique Zuñiga', 'author_url...",NaN,https://www.vidanta.com/web/nuevo-vallarta/the...,[],[],NaN
freq,646,23,617,4,167,1,1,23,NaN,1,...,NaN,13,4,NaN,1,NaN,3,204,204,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.431222,NaN,...,2.0,NaN,NaN,4.430317,NaN,323.083710,NaN,NaN,NaN,2.0
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.590839,NaN,...,NaN,NaN,NaN,0.590503,NaN,813.402238,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,...,2.0,NaN,NaN,1.000000,NaN,1.000000,NaN,NaN,NaN,2.0
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.200000,NaN,...,2.0,NaN,NaN,4.200000,NaN,4.000000,NaN,NaN,NaN,2.0
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.500000,NaN,...,2.0,NaN,NaN,4.500000,NaN,22.500000,NaN,NaN,NaN,2.0
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.875000,NaN,...,2.0,NaN,NaN,4.800000,NaN,157.250000,NaN,NaN,NaN,2.0
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,NaN,...,2.0,NaN,NaN,5.000000,NaN,6217.000000,NaN,NaN,NaN,2.0

In [9]:
df1.head()

,business_status,geometry,icon,name_x,opening_hours,photos,place_id,plus_code,rating_x,reference,...,price_level_x,international_phone_number,name_y,rating_y,reviews,user_ratings_total_y,website,all_ratings,all_reviews,price_level_y
0,OPERATIONAL,"{'location': {'lat': 20.6939009, 'lng': -105.2...",https://maps.gstatic.com/mapfiles/place_api/ic...,casa LAS PIÑAS,{'open_now': False},"[{'height': 640, 'html_attributions': ['<a hre...",ChIJIeVYvYNGIYQRh-9bPVK3fCU,"{'compound_code': 'MPVG+H8 Jarretaderas, Nayar...",4.6,ChIJIeVYvYNGIYQRh-9bPVK3fCU,...,NaN,+52 322 102 8516,casa LAS PIÑAS,4.6,"[{'author_name': 'Jovita Garcia Fernandez', 'a...",8.0,https://www.facebook.com/departamentos.laspinas/,"[5, 5, 5, 5, 5]","['An excellent place has all the comforts', 'I...",NaN
1,OPERATIONAL,"{'location': {'lat': 20.6920731, 'lng': -105.2...",https://maps.gstatic.com/mapfiles/place_api/ic...,Villas Victoria Confort Jarretaderas,{'open_now': True},NaN,ChIJdSKPg3xHIYQRlZ0pmfgVPiQ,"{'compound_code': 'MPRG+R4 Jarretaderas, Nayar...",5.0,ChIJdSKPg3xHIYQRlZ0pmfgVPiQ,...,NaN,+52 322 297 0093,Villas Victoria Confort Jarretaderas,5.0,"[{'author_name': 'anahi chavez', 'author_url':...",1.0,https://www.villasvictoriacomfort.com/,[5],"['It was more than I expected! Cheap, spacious...",NaN
2,OPERATIONAL,"{'location': {'lat': 20.689785, 'lng': -105.27...",https://maps.gstatic.com/mapfiles/place_api/ic...,Lada telefonica,NaN,NaN,ChIJ8RLPC-VHIYQR8Bw635S5JCo,"{'compound_code': 'MPQF+W9 Las Juntas, Jalisco...",NaN,ChIJ8RLPC-VHIYQR8Bw635S5JCo,...,NaN,+57 301 4649339,Lada telefonica,NaN,NaN,NaN,NaN,[],[],NaN
3,OPERATIONAL,"{'location': {'lat': 20.6939068, 'lng': -105.2...",https://maps.gstatic.com/mapfiles/place_api/ic...,Hotel Posada Alejandra,NaN,"[{'height': 349, 'html_attributions': ['<a hre...",ChIJB2Yha4NGIYQRE-GTtF_VSAU,"{'compound_code': 'MPVF+HF Jarretaderas, Nayar...",4.0,ChIJB2Yha4NGIYQRE-GTtF_VSAU,...,NaN,+52 322 135 6145,Hotel Posada Alejandra,4.0,"[{'author_name': 'Juan Carlos Lopez', 'author_...",54.0,https://www.google.com/url?sa=t&source=web&rct...,"[3, 4, 3, 3, 5]","[""Just for one night it's alright"", 'Discreet'...",NaN
4,OPERATIONAL,"{'location': {'lat': 20.6938115, 'lng': -105.2...",https://maps.gstatic.com/mapfiles/place_api/ic...,casa LAS PIÑAS,NaN,NaN,ChIJHd0vt_1HIYQRQxgGpgI4Oi0,"{'compound_code': 'MPVG+G5 Jarretaderas, Nayar...",NaN,ChIJHd0vt_1HIYQRQxgGpgI4Oi0,...,NaN,NaN,casa LAS PIÑAS,NaN,NaN,NaN,NaN,[],[],NaN

In [10]:
df1 = df1[df1['all_reviews']!="[]"]

In [11]:
df1.shape

(442, 24)

In [12]:
df1.head()

,business_status,geometry,icon,name_x,opening_hours,photos,place_id,plus_code,rating_x,reference,...,price_level_x,international_phone_number,name_y,rating_y,reviews,user_ratings_total_y,website,all_ratings,all_reviews,price_level_y
0,OPERATIONAL,"{'location': {'lat': 20.6939009, 'lng': -105.2...",https://maps.gstatic.com/mapfiles/place_api/ic...,casa LAS PIÑAS,{'open_now': False},"[{'height': 640, 'html_attributions': ['<a hre...",ChIJIeVYvYNGIYQRh-9bPVK3fCU,"{'compound_code': 'MPVG+H8 Jarretaderas, Nayar...",4.6,ChIJIeVYvYNGIYQRh-9bPVK3fCU,...,NaN,+52 322 102 8516,casa LAS PIÑAS,4.6,"[{'author_name': 'Jovita Garcia Fernandez', 'a...",8.0,https://www.facebook.com/departamentos.laspinas/,"[5, 5, 5, 5, 5]","['An excellent place has all the comforts', 'I...",NaN
1,OPERATIONAL,"{'location': {'lat': 20.6920731, 'lng': -105.2...",https://maps.gstatic.com/mapfiles/place_api/ic...,Villas Victoria Confort Jarretaderas,{'open_now': True},NaN,ChIJdSKPg3xHIYQRlZ0pmfgVPiQ,"{'compound_code': 'MPRG+R4 Jarretaderas, Nayar...",5.0,ChIJdSKPg3xHIYQRlZ0pmfgVPiQ,...,NaN,+52 322 297 0093,Villas Victoria Confort Jarretaderas,5.0,"[{'author_name': 'anahi chavez', 'author_url':...",1.0,https://www.villasvictoriacomfort.com/,[5],"['It was more than I expected! Cheap, spacious...",NaN
3,OPERATIONAL,"{'location': {'lat': 20.6939068, 'lng': -105.2...",https://maps.gstatic.com/mapfiles/place_api/ic...,Hotel Posada Alejandra,NaN,"[{'height': 349, 'html_attributions': ['<a hre...",ChIJB2Yha4NGIYQRE-GTtF_VSAU,"{'compound_code': 'MPVF+HF Jarretaderas, Nayar...",4.0,ChIJB2Yha4NGIYQRE-GTtF_VSAU,...,NaN,+52 322 135 6145,Hotel Posada Alejandra,4.0,"[{'author_name': 'Juan Carlos Lopez', 'author_...",54.0,https://www.google.com/url?sa=t&source=web&rct...,"[3, 4, 3, 3, 5]","[""Just for one night it's alright"", 'Discreet'...",NaN
5,OPERATIONAL,"{'location': {'lat': 20.6241471, 'lng': -105.2...",https://maps.gstatic.com/mapfiles/place_api/ic...,Hotel Azul Romero,{'open_now': True},"[{'height': 3120, 'html_attributions': ['<a hr...",ChIJFW5JHF5FIYQRogsYTW-KvMI,"{'compound_code': 'JQFG+M7 Puerto Vallarta, Ja...",3.9,ChIJFW5JHF5FIYQRogsYTW-KvMI,...,NaN,+52 322 276 4854,Hotel Azul Romero,3.9,"[{'author_name': 'Al Reust', 'author_url': 'ht...",11.0,http://www.azulromero.com/,"[3, 4, 5, 4, 1]","['This is interesting, as it appears to be be ...",NaN
9,OPERATIONAL,"{'location': {'lat': 20.6225929, 'lng': -105.2...",https://maps.gstatic.com/mapfiles/place_api/ic...,Vacational Apartment Apartamento Vacacional De...,NaN,"[{'height': 1052, 'html_attributions': ['<a hr...",ChIJ9321RV5FIYQRwnf0qJkeIqU,"{'compound_code': 'JQFG+2M Puerto Vallarta, Ja...",4.8,ChIJ9321RV5FIYQRwnf0qJkeIqU,...,NaN,+52 322 270 9397,Vacational Apartment Apartamento Vacacional De...,4.8,"[{'author_name': 'Daniel Chilldres', 'author_u...",11.0,https://www.airbnb.mx/rooms/23351610,"[5, 4, 5, 5, 5]","['I loved it here!', 'The place is clean, plea...",NaN

In [13]:
df1 = df1.reset_index(drop=True)

In [14]:
df1.shape

(442, 24)

In [15]:
df1.head()

,business_status,geometry,icon,name_x,opening_hours,photos,place_id,plus_code,rating_x,reference,...,price_level_x,international_phone_number,name_y,rating_y,reviews,user_ratings_total_y,website,all_ratings,all_reviews,price_level_y
0,OPERATIONAL,"{'location': {'lat': 20.6939009, 'lng': -105.2...",https://maps.gstatic.com/mapfiles/place_api/ic...,casa LAS PIÑAS,{'open_now': False},"[{'height': 640, 'html_attributions': ['<a hre...",ChIJIeVYvYNGIYQRh-9bPVK3fCU,"{'compound_code': 'MPVG+H8 Jarretaderas, Nayar...",4.6,ChIJIeVYvYNGIYQRh-9bPVK3fCU,...,NaN,+52 322 102 8516,casa LAS PIÑAS,4.6,"[{'author_name': 'Jovita Garcia Fernandez', 'a...",8.0,https://www.facebook.com/departamentos.laspinas/,"[5, 5, 5, 5, 5]","['An excellent place has all the comforts', 'I...",NaN
1,OPERATIONAL,"{'location': {'lat': 20.6920731, 'lng': -105.2...",https://maps.gstatic.com/mapfiles/place_api/ic...,Villas Victoria Confort Jarretaderas,{'open_now': True},NaN,ChIJdSKPg3xHIYQRlZ0pmfgVPiQ,"{'compound_code': 'MPRG+R4 Jarretaderas, Nayar...",5.0,ChIJdSKPg3xHIYQRlZ0pmfgVPiQ,...,NaN,+52 322 297 0093,Villas Victoria Confort Jarretaderas,5.0,"[{'author_name': 'anahi chavez', 'author_url':...",1.0,https://www.villasvictoriacomfort.com/,[5],"['It was more than I expected! Cheap, spacious...",NaN
2,OPERATIONAL,"{'location': {'lat': 20.6939068, 'lng': -105.2...",https://maps.gstatic.com/mapfiles/place_api/ic...,Hotel Posada Alejandra,NaN,"[{'height': 349, 'html_attributions': ['<a hre...",ChIJB2Yha4NGIYQRE-GTtF_VSAU,"{'compound_code': 'MPVF+HF Jarretaderas, Nayar...",4.0,ChIJB2Yha4NGIYQRE-GTtF_VSAU,...,NaN,+52 322 135 6145,Hotel Posada Alejandra,4.0,"[{'author_name': 'Juan Carlos Lopez', 'author_...",54.0,https://www.google.com/url?sa=t&source=web&rct...,"[3, 4, 3, 3, 5]","[""Just for one night it's alright"", 'Discreet'...",NaN
3,OPERATIONAL,"{'location': {'lat': 20.6241471, 'lng': -105.2...",https://maps.gstatic.com/mapfiles/place_api/ic...,Hotel Azul Romero,{'open_now': True},"[{'height': 3120, 'html_attributions': ['<a hr...",ChIJFW5JHF5FIYQRogsYTW-KvMI,"{'compound_code': 'JQFG+M7 Puerto Vallarta, Ja...",3.9,ChIJFW5JHF5FIYQRogsYTW-KvMI,...,NaN,+52 322 276 4854,Hotel Azul Romero,3.9,"[{'author_name': 'Al Reust', 'author_url': 'ht...",11.0,http://www.azulromero.com/,"[3, 4, 5, 4, 1]","['This is interesting, as it appears to be be ...",NaN
4,OPERATIONAL,"{'location': {'lat': 20.6225929, 'lng': -105.2...",https://maps.gstatic.com/mapfiles/place_api/ic...,Vacational Apartment Apartamento Vacacional De...,NaN,"[{'height': 1052, 'html_attributions': ['<a hr...",ChIJ9321RV5FIYQRwnf0qJkeIqU,"{'compound_code': 'JQFG+2M Puerto Vallarta, Ja...",4.8,ChIJ9321RV5FIYQRwnf0qJkeIqU,...,NaN,+52 322 270 9397,Vacational Apartment Apartamento Vacacional De...,4.8,"[{'author_name': 'Daniel Chilldres', 'author_u...",11.0,https://www.airbnb.mx/rooms/23351610,"[5, 4, 5, 5, 5]","['I loved it here!', 'The place is clean, plea...",NaN

In [16]:
df1.describe(include='all')

,business_status,geometry,icon,name_x,opening_hours,photos,place_id,plus_code,rating_x,reference,...,price_level_x,international_phone_number,name_y,rating_y,reviews,user_ratings_total_y,website,all_ratings,all_reviews,price_level_y
count,442,442,442,442,189,385,442,440,442.000000,442,...,1.0,363,442,442.000000,442,442.000000,288,442,442,1.0
unique,1,436,4,436,2,385,442,420,NaN,442,...,NaN,337,436,NaN,442,NaN,281,213,392,NaN
top,OPERATIONAL,"{'location': {'lat': 20.65340699999999, 'lng':...",https://maps.gstatic.com/mapfiles/place_api/ic...,Villa Azul Celeste,{'open_now': True},"[{'height': 766, 'html_attributions': ['<a hre...",ChIJH07bwLxFIYQRwnD_-wmnVPE,"{'compound_code': 'MQ3F+9V Puerto Vallarta, Ja...",NaN,ChIJH07bwLxFIYQRwnD_-wmnVPE,...,NaN,+52 322 226 4000,Villa Azul Celeste,NaN,"[{'author_name': 'Enrique Zuñiga', 'author_url...",NaN,https://www.vidanta.com/web/nuevo-vallarta,"[5, 5, 5, 5, 5]",[''],NaN
freq,442,6,416,3,146,1,1,6,NaN,1,...,NaN,10,3,NaN,1,NaN,3,68,39,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.431222,NaN,...,2.0,NaN,NaN,4.430317,NaN,323.083710,NaN,NaN,NaN,2.0
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.590839,NaN,...,NaN,NaN,NaN,0.590503,NaN,813.402238,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,...,2.0,NaN,NaN,1.000000,NaN,1.000000,NaN,NaN,NaN,2.0
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.200000,NaN,...,2.0,NaN,NaN,4.200000,NaN,4.000000,NaN,NaN,NaN,2.0
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.500000,NaN,...,2.0,NaN,NaN,4.500000,NaN,22.500000,NaN,NaN,NaN,2.0
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.875000,NaN,...,2.0,NaN,NaN,4.800000,NaN,157.250000,NaN,NaN,NaN,2.0
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,NaN,...,2.0,NaN,NaN,5.000000,NaN,6217.000000,NaN,NaN,NaN,2.0

In [17]:
df1 = df1[df1['all_reviews']!="['']"]

In [18]:
df1.describe(include='all')

,business_status,geometry,icon,name_x,opening_hours,photos,place_id,plus_code,rating_x,reference,...,price_level_x,international_phone_number,name_y,rating_y,reviews,user_ratings_total_y,website,all_ratings,all_reviews,price_level_y
count,403,403,403,403,185,368,403,401,403.000000,403,...,1.0,340,403,403.00000,403,403.000000,272,403,403,1.0
unique,1,399,4,399,2,368,403,387,NaN,403,...,NaN,317,399,NaN,403,NaN,266,211,391,NaN
top,OPERATIONAL,"{'location': {'lat': 20.65340699999999, 'lng':...",https://maps.gstatic.com/mapfiles/place_api/ic...,Puerto Vallarta,{'open_now': True},"[{'height': 766, 'html_attributions': ['<a hre...",ChIJH07bwLxFIYQRwnD_-wmnVPE,"{'compound_code': 'MQ3F+9V Puerto Vallarta, Ja...",NaN,ChIJH07bwLxFIYQRwnD_-wmnVPE,...,NaN,+52 322 226 4000,Puerto Vallarta,NaN,"[{'author_name': 'Goliat911 Rodriguez', 'autho...",NaN,https://www.vidanta.com/web/nuevo-vallarta,"[5, 5, 5, 5, 5]","['', '']",NaN
freq,403,4,378,2,142,1,1,4,NaN,1,...,NaN,10,2,NaN,1,NaN,3,68,8,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.418362,NaN,...,2.0,NaN,NaN,4.41737,NaN,354.253102,NaN,NaN,NaN,2.0
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.526899,NaN,...,NaN,NaN,NaN,0.52646,NaN,845.442164,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,...,2.0,NaN,NaN,1.00000,NaN,1.000000,NaN,NaN,NaN,2.0
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.200000,NaN,...,2.0,NaN,NaN,4.20000,NaN,5.500000,NaN,NaN,NaN,2.0
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.500000,NaN,...,2.0,NaN,NaN,4.50000,NaN,29.000000,NaN,NaN,NaN,2.0
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.800000,NaN,...,2.0,NaN,NaN,4.80000,NaN,186.500000,NaN,NaN,NaN,2.0
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,NaN,...,2.0,NaN,NaN,5.00000,NaN,6217.000000,NaN,NaN,NaN,2.0

In [19]:
df1 = df1[df1['all_reviews']!="['', '']"]

In [20]:
df1.describe(include='all')

,business_status,geometry,icon,name_x,opening_hours,photos,place_id,plus_code,rating_x,reference,...,price_level_x,international_phone_number,name_y,rating_y,reviews,user_ratings_total_y,website,all_ratings,all_reviews,price_level_y
count,395,395,395,395,185,366,395,394,395.000000,395,...,1.0,335,395,395.000000,395,395.000000,268,395,395,1.0
unique,1,392,4,391,2,366,395,380,NaN,395,...,NaN,313,391,NaN,395,NaN,262,208,390,NaN
top,OPERATIONAL,"{'location': {'lat': 20.65340699999999, 'lng':...",https://maps.gstatic.com/mapfiles/place_api/ic...,Hyatt Ziva Puerto Vallarta,{'open_now': True},"[{'height': 766, 'html_attributions': ['<a hre...",ChIJH07bwLxFIYQRwnD_-wmnVPE,"{'compound_code': 'MQ3F+9V Puerto Vallarta, Ja...",NaN,ChIJH07bwLxFIYQRwnD_-wmnVPE,...,NaN,+52 322 226 4000,Hyatt Ziva Puerto Vallarta,NaN,"[{'author_name': 'Goliat911 Rodriguez', 'autho...",NaN,https://www.vidanta.com/web/nuevo-vallarta,"[5, 5, 5, 5, 5]","['', '', '']",NaN
freq,395,3,371,2,142,1,1,4,NaN,1,...,NaN,10,2,NaN,1,NaN,3,68,3,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.425570,NaN,...,2.0,NaN,NaN,4.424557,NaN,361.387342,NaN,NaN,NaN,2.0
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.500892,NaN,...,NaN,NaN,NaN,0.500436,NaN,852.475886,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,...,2.0,NaN,NaN,1.000000,NaN,1.000000,NaN,NaN,NaN,2.0
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.200000,NaN,...,2.0,NaN,NaN,4.200000,NaN,6.000000,NaN,NaN,NaN,2.0
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.500000,NaN,...,2.0,NaN,NaN,4.500000,NaN,32.000000,NaN,NaN,NaN,2.0
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.800000,NaN,...,2.0,NaN,NaN,4.800000,NaN,188.000000,NaN,NaN,NaN,2.0
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,NaN,...,2.0,NaN,NaN,5.000000,NaN,6217.000000,NaN,NaN,NaN,2.0

In [21]:
df1 = df1[df1['all_reviews']!="['', '', '']"]

In [22]:
df1.describe(include='all')

,business_status,geometry,icon,name_x,opening_hours,photos,place_id,plus_code,rating_x,reference,...,price_level_x,international_phone_number,name_y,rating_y,reviews,user_ratings_total_y,website,all_ratings,all_reviews,price_level_y
count,392,392,392,392,184,364,392,391,392.000000,392,...,1.0,333,392,392.000000,392,392.000000,268,392,392,1.0
unique,1,389,4,388,2,364,392,377,NaN,392,...,NaN,311,388,NaN,392,NaN,262,207,389,NaN
top,OPERATIONAL,"{'location': {'lat': 20.65340699999999, 'lng':...",https://maps.gstatic.com/mapfiles/place_api/ic...,Hyatt Ziva Puerto Vallarta,{'open_now': True},"[{'height': 766, 'html_attributions': ['<a hre...",ChIJH07bwLxFIYQRwnD_-wmnVPE,"{'compound_code': 'MQ3F+9V Puerto Vallarta, Ja...",NaN,ChIJH07bwLxFIYQRwnD_-wmnVPE,...,NaN,+52 322 226 4000,Hyatt Ziva Puerto Vallarta,NaN,[{'author_name': 'Luis Alberto Morales Sanchez...,NaN,https://www.vidanta.com/web/nuevo-vallarta,"[5, 5, 5, 5, 5]","['', '', '', '']",NaN
freq,392,3,368,2,141,1,1,4,NaN,1,...,NaN,10,2,NaN,1,NaN,3,68,3,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.425255,NaN,...,2.0,NaN,NaN,4.424235,NaN,364.130102,NaN,NaN,NaN,2.0
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.500435,NaN,...,NaN,NaN,NaN,0.499974,NaN,855.159593,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,...,2.0,NaN,NaN,1.000000,NaN,1.000000,NaN,NaN,NaN,2.0
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.200000,NaN,...,2.0,NaN,NaN,4.200000,NaN,6.000000,NaN,NaN,NaN,2.0
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.500000,NaN,...,2.0,NaN,NaN,4.500000,NaN,33.000000,NaN,NaN,NaN,2.0
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.800000,NaN,...,2.0,NaN,NaN,4.800000,NaN,188.500000,NaN,NaN,NaN,2.0
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,NaN,...,2.0,NaN,NaN,5.000000,NaN,6217.000000,NaN,NaN,NaN,2.0

In [23]:
df1 = df1[df1['all_reviews']!="['', '', '', '']"]

In [24]:
df1.describe(include='all')

,business_status,geometry,icon,name_x,opening_hours,photos,place_id,plus_code,rating_x,reference,...,price_level_x,international_phone_number,name_y,rating_y,reviews,user_ratings_total_y,website,all_ratings,all_reviews,price_level_y
count,389,389,389,389,183,362,389,388,389.000000,389,...,1.0,330,389,389.000000,389,389.000000,265,389,389,1.0
unique,1,386,4,385,2,362,389,374,NaN,389,...,NaN,309,385,NaN,389,NaN,259,204,388,NaN
top,OPERATIONAL,"{'location': {'lat': 20.65340699999999, 'lng':...",https://maps.gstatic.com/mapfiles/place_api/ic...,Casa Corazon,{'open_now': True},"[{'height': 766, 'html_attributions': ['<a hre...",ChIJH07bwLxFIYQRwnD_-wmnVPE,"{'compound_code': 'MQ3F+9V Puerto Vallarta, Ja...",NaN,ChIJH07bwLxFIYQRwnD_-wmnVPE,...,NaN,+52 322 226 4000,Casa Corazon,NaN,[{'author_name': 'Luis Alberto Morales Sanchez...,NaN,https://www.vidanta.com/web/nuevo-vallarta,"[5, 5, 5, 5, 5]",['Good'],NaN
freq,389,3,366,2,140,1,1,4,NaN,1,...,NaN,10,2,NaN,1,NaN,3,68,2,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.425450,NaN,...,2.0,NaN,NaN,4.424422,NaN,366.910026,NaN,NaN,NaN,2.0
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.501693,NaN,...,NaN,NaN,NaN,0.501230,NaN,857.869397,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,...,2.0,NaN,NaN,1.000000,NaN,1.000000,NaN,NaN,NaN,2.0
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.200000,NaN,...,2.0,NaN,NaN,4.200000,NaN,7.000000,NaN,NaN,NaN,2.0
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.500000,NaN,...,2.0,NaN,NaN,4.500000,NaN,33.000000,NaN,NaN,NaN,2.0
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.800000,NaN,...,2.0,NaN,NaN,4.800000,NaN,190.000000,NaN,NaN,NaN,2.0
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,NaN,...,2.0,NaN,NaN,5.000000,NaN,6217.000000,NaN,NaN,NaN,2.0

In [25]:
df1 = df1[df1['all_reviews']!="['Good']"]

In [26]:
df1.describe(include='all')

,business_status,geometry,icon,name_x,opening_hours,photos,place_id,plus_code,rating_x,reference,...,price_level_x,international_phone_number,name_y,rating_y,reviews,user_ratings_total_y,website,all_ratings,all_reviews,price_level_y
count,387,387,387,387,183,361,387,386,387.000000,387,...,1.0,329,387,387.000000,387,387.000000,265,387,387,1.0
unique,1,384,4,383,2,361,387,372,NaN,387,...,NaN,308,383,NaN,387,NaN,259,204,387,NaN
top,OPERATIONAL,"{'location': {'lat': 20.65340699999999, 'lng':...",https://maps.gstatic.com/mapfiles/place_api/ic...,Casa Corazon,{'open_now': True},"[{'height': 766, 'html_attributions': ['<a hre...",ChIJH07bwLxFIYQRwnD_-wmnVPE,"{'compound_code': 'MQ3F+9V Puerto Vallarta, Ja...",NaN,ChIJH07bwLxFIYQRwnD_-wmnVPE,...,NaN,+52 322 226 4000,Casa Corazon,NaN,[{'author_name': 'Luis Alberto Morales Sanchez...,NaN,https://www.vidanta.com/web/nuevo-vallarta,"[5, 5, 5, 5, 5]","[""Should be zero stars if at all possible. Dur...",NaN
freq,387,3,364,2,140,1,1,4,NaN,1,...,NaN,10,2,NaN,1,NaN,3,68,1,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.425065,NaN,...,2.0,NaN,NaN,4.424031,NaN,368.801034,NaN,NaN,NaN,2.0
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.501673,NaN,...,NaN,NaN,NaN,0.501207,NaN,859.683515,NaN,NaN,NaN,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,...,2.0,NaN,NaN,1.000000,NaN,1.000000,NaN,NaN,NaN,2.0
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.200000,NaN,...,2.0,NaN,NaN,4.200000,NaN,7.000000,NaN,NaN,NaN,2.0
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.500000,NaN,...,2.0,NaN,NaN,4.500000,NaN,33.000000,NaN,NaN,NaN,2.0
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.800000,NaN,...,2.0,NaN,NaN,4.800000,NaN,190.000000,NaN,NaN,NaN,2.0
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,NaN,...,2.0,NaN,NaN,5.000000,NaN,6217.000000,NaN,NaN,NaN,2.0

In [28]:
df1.head(20)

,business_status,geometry,icon,name_x,opening_hours,photos,place_id,plus_code,rating_x,reference,...,price_level_x,international_phone_number,name_y,rating_y,reviews,user_ratings_total_y,website,all_ratings,all_reviews,price_level_y
0,OPERATIONAL,"{'location': {'lat': 20.6939009, 'lng': -105.2...",https://maps.gstatic.com/mapfiles/place_api/ic...,casa LAS PIÑAS,{'open_now': False},"[{'height': 640, 'html_attributions': ['<a hre...",ChIJIeVYvYNGIYQRh-9bPVK3fCU,"{'compound_code': 'MPVG+H8 Jarretaderas, Nayar...",4.6,ChIJIeVYvYNGIYQRh-9bPVK3fCU,...,NaN,+52 322 102 8516,casa LAS PIÑAS,4.6,"[{'author_name': 'Jovita Garcia Fernandez', 'a...",8.0,https://www.facebook.com/departamentos.laspinas/,"[5, 5, 5, 5, 5]","['An excellent place has all the comforts', 'I...",NaN
1,OPERATIONAL,"{'location': {'lat': 20.6920731, 'lng': -105.2...",https://maps.gstatic.com/mapfiles/place_api/ic...,Villas Victoria Confort Jarretaderas,{'open_now': True},NaN,ChIJdSKPg3xHIYQRlZ0pmfgVPiQ,"{'compound_code': 'MPRG+R4 Jarretaderas, Nayar...",5.0,ChIJdSKPg3xHIYQRlZ0pmfgVPiQ,...,NaN,+52 322 297 0093,Villas Victoria Confort Jarretaderas,5.0,"[{'author_name': 'anahi chavez', 'author_url':...",1.0,https://www.villasvictoriacomfort.com/,[5],"['It was more than I expected! Cheap, spacious...",NaN
2,OPERATIONAL,"{'location': {'lat': 20.6939068, 'lng': -105.2...",https://maps.gstatic.com/mapfiles/place_api/ic...,Hotel Posada Alejandra,NaN,"[{'height': 349, 'html_attributions': ['<a hre...",ChIJB2Yha4NGIYQRE-GTtF_VSAU,"{'compound_code': 'MPVF+HF Jarretaderas, Nayar...",4.0,ChIJB2Yha4NGIYQRE-GTtF_VSAU,...,NaN,+52 322 135 6145,Hotel Posada Alejandra,4.0,"[{'author_name': 'Juan Carlos Lopez', 'author_...",54.0,https://www.google.com/url?sa=t&source=web&rct...,"[3, 4, 3, 3, 5]","[""Just for one night it's alright"", 'Discreet'...",NaN
3,OPERATIONAL,"{'location': {'lat': 20.6241471, 'lng': -105.2...",https://maps.gstatic.com/mapfiles/place_api/ic...,Hotel Azul Romero,{'open_now': True},"[{'height': 3120, 'html_attributions': ['<a hr...",ChIJFW5JHF5FIYQRogsYTW-KvMI,"{'compound_code': 'JQFG+M7 Puerto Vallarta, Ja...",3.9,ChIJFW5JHF5FIYQRogsYTW-KvMI,...,NaN,+52 322 276 4854,Hotel Azul Romero,3.9,"[{'author_name': 'Al Reust', 'author_url': 'ht...",11.0,http://www.azulromero.com/,"[3, 4, 5, 4, 1]","['This is interesting, as it appears to be be ...",NaN
4,OPERATIONAL,"{'location': {'lat': 20.6225929, 'lng': -105.2...",https://maps.gstatic.com/mapfiles/place_api/ic...,Vacational Apartment Apartamento Vacacional De...,NaN,"[{'height': 1052, 'html_attributions': ['<a hr...",ChIJ9321RV5FIYQRwnf0qJkeIqU,"{'compound_code': 'JQFG+2M Puerto Vallarta, Ja...",4.8,ChIJ9321RV5FIYQRwnf0qJkeIqU,...,NaN,+52 322 270 9397,Vacational Apartment Apartamento Vacacional De...,4.8,"[{'author_name': 'Daniel Chilldres', 'author_u...",11.0,https://www.airbnb.mx/rooms/23351610,"[5, 4, 5, 5, 5]","['I loved it here!', 'The place is clean, plea...",NaN
5,OPERATIONAL,"{'location': {'lat': 20.6272548, 'lng': -105.2...",https://maps.gstatic.com/mapfiles/place_api/ic...,Condominio Pajaritos,NaN,"[{'height': 4032, 'html_attributions': ['<a hr...",ChIJ23uXKGFFIYQRJxkSIttEGfQ,"{'compound_code': 'JQGG+WC Puerto Vallarta, Ja...",4.4,ChIJ23uXKGFFIYQRJxkSIttEGfQ,...,NaN,NaN,Condominio Pajaritos,4.4,"[{'author_name': 'Keith Grohowski', 'author_ur...",30.0,http://abnb.me/EVmg/3ScTVfRGDz,"[5, 5, 5, 4, 4]",['Great place to stay. Spent time here in an a...,NaN
6,OPERATIONAL,"{'location': {'lat': 20.6221949, 'lng': -105.2...",https://maps.gstatic.com/mapfiles/place_api/ic...,HOTEL LIBRAMIENTO,{'open_now': True},"[{'height': 756, 'html_attributions': ['<a hre...",ChIJB9b8Ul5FIYQRJilneH52wCE,"{'compound_code': 'JQCG+VV Puerto Vallarta, Ja...",3.8,ChIJB9b8Ul5FIYQRJilneH52wCE,...,NaN,+52 322 223 1437,HOTEL LIBRAMIENTO,3.8,"[{'author_name': 'DA AG', 'author_url': 'https...",75.0,NaN,"[3, 1, 1, 4, 5]","['Aight', 'Bad attitude of service offensive d...",NaN
7,OPERATIONAL,"{'location': {'lat': 20.6254901, 'lng': -105.2...",https://maps.gstatic.com/mapfiles/place_api/ic...,Motel Los Angeles,NaN,"[{'height': 4160, 'html_attributions': ['<a hr...",ChIJayo8iWBFIYQRooYalPlLsMc,"{'compound_code': 'JQGG+5X Puerto Vallarta, Ja...",3.9,ChIJayo8iWBFIYQRooYalPlLsMc,...,NaN,+52 322 225 0511,Motel Los Angeles,3.9,"[{'author_name': 'Chelo Garnier', 'author_url'...",140.0,NaN,"[2, 1, 5, 5, 5]","['The Motel is... Good for what is worth in ""l...",NaN
8,OPERATIONAL,"{'location': {'lat': 20.6208631, 'lng': -105.2...",https://maps.gstatic.com/mapfiles/place_api/ic...,Hotel tunel puerto Vallarta Jalisco.,{'open_now': True},"[{'height': 3072, 'html_attributions': ['<a hr...",ChIJMzxy515FIYQRhJ1m3Vig1gE,"{'compound_code': 'JQCG+8W Puerto Vallarta, Ja...",3.3,ChIJMzxy515FIYQRhJ1m3Vig1gE,...,NaN,+52 322 222 0710,Hotel tunel puerto Vallarta Jalisco.,3.3,[{'author_name': 'Diana Monserrat Veliz Renter...,18.0,https://hotel-tunel.negocio.site/,"[1, 1, 5, 2, 1]","['Bad hygiene, torn towels, the air conditioni...",NaN
9,OPERATIONAL,"{'location': {'lat': 20.6267224, 'lng': -105.2...",https://maps.gstatic.com/mapfiles/place_api/ic...,Blue Chairs Resort by the Sea,NaN,"[{'height': 3024, 'html_attributions': ['<a hr...",ChIJg4FQmYpPIYQRQ99untxWus8,NaN,3.3,ChIJg4FQmYpPIYQRQ99untxWus8,...,NaN,NaN,Blue Chairs Resort by the Sea,3.3,"[{'author_name': 'Shady Bee', 'author_url': 'h...",3.0,http://www.bluechairsresortbythesea.com/locati...,"[4, 5, 1]","['Good time. A little close to other guests.',...",NaN
10,OPERATIONAL,"{'location': {'lat': 20.627761, 'lng': -105.22...",https://maps.gstatic.com/mapfiles/place_api/ic...,Casa Ortega,{'open_now': False},"[{'height': 720, 'html_attributions': ['<a hre...",ChIJNR9UzWFFIYQRfKudM0sRI0Y,"{'compound_code': 'JQHH+4W Puerto Vallarta, Ja...",4.8,ChIJNR9UzWFFIYQRfKudM0sRI0Y,...,NaN,+52 322 302 9066,Casa Ortega,4.8,"[{'author_name': 'Armando OroFra', 'author_url...",4.0,https://casaortega.mxhotel.site/,"[5, 5, 4, 5]",['Very good cost and spacious house for groups...,NaN
11,OPERATIONAL,"{'location': {'lat': 20.6349484, 'lng': -105.2...",https://maps.gstatic.com/mapfiles/place_api/ic...,Villa Lujosa en Puerto Vallarta,NaN,"[{'height': 4096, 'html_attributions': ['<a hr...",ChIJb-1u3mJFIYQRQaRjfONmOJg,"{'compound_code': 'JQMH+X5 Puerto Vallarta, Ja...",4.5,ChIJb-1u3mJFIYQRQaRjfONmOJg,...,NaN,+52 322 235 8066,Villa Lujosa en Puerto Vallarta,4.5,"[{'author_name': 'hugo peña', 'author_url': 'h...",19.0,NaN,"[5, 3, 5, 5, 5]","['Cool', 'If you are looking for a super quiet...",NaN
12,OPERATIONAL,"{'location': {'lat': 20.6314507, 'lng': -105.2...",https://maps.gstatic.com/mapfiles/place_api/ic...,plaza central sur 150,NaN,NaN,ChIJzf0oz2NFIYQRuvlEAs6g2Fg,"{'compound_code': 'JQJG+HR Puerto Vallarta, Ja...",5.0,ChIJzf0oz2NFIYQRuvlEAs6g2Fg,...,NaN,NaN,plaza central sur 150,5.0,"[{'author_name': 'Sebastian Yañez', 'author_ur...",1.0,NaN,[5],"['Quiet, humble and very safe neighborhood']",NaN
13,OPERATIONAL,"{'location': {'lat': 20.632041, 'lng': -105.22...",https://maps.gstatic.com/mapfiles/place_api/ic...,Vacation Home Rentals Vallarta,{'open_now': False},"[{'height': 466, 'html_attributions': ['<a hre...",ChIJ5aGKjWNFIYQR0_SwG_f_Hg4,"{'compound_code': 'JQJG+R6 Puerto Vallarta, Ja...",4.3,ChIJ5aGKjWNFIYQR0_SwG_f_Hg4,...,NaN,+52 322 224 3621,Vacation Home Rentals Vallarta,4.3,[{'author_name': 'Gerardo Israel Martínez Álva...,4.0,NaN,"[5, 5, 5, 2]",['We really enjoyed our time at Vacation Home ...,NaN
15,OPERATIONAL,"{'location': {'lat': 20.6336142, 'lng': -105.2...",https://maps.gstatic.com/mapfiles/place_api/ic...,Apartamentos Lisboa,{'open_now': False},"[{'height': 3456, 'html_attributions': ['<a hr...",ChIJT--Qj2RFIYQRCkuXi7C7zKI,"{'compound_code': 'JQMF+CH Puerto Vallarta, Ja...",5.0,ChIJT--Qj2RFIYQRCkuXi7C7zKI,...,NaN,NaN,Apartamentos Lisboa,5.0,"[{'author_name': 'Joseluis Avila', 'author_url...",6.0,NaN,"[5, 5, 5, 5, 5]","['Good service and comfortable price', '', '',...",NaN
16,OPERATIONAL,"{'location': {'lat': 20.6390896, 'lng': -105.2...",https://maps.gstatic.com/mapfiles/place_api/ic...,Casa de Ambrose,NaN,"[{'height': 4032, 'html_attributions': ['<a hr...",ChIJ235toodPIYQR5p5YsYiRf2c,"{'compound_code': 'JQQJ+JR Puerto Vallarta, Ja...",4.8,ChIJ235toodPIYQR5p5YsYiRf2c,...,NaN,+52 322 151 6119,Casa de Ambrose,4.8,"[{'author_name': 'Paul Gekides', 'author_url':...",5.0,NaN,"[5, 5, 4, 5, 5]",['Can someone tell me how to contact the hotel...,NaN
18,OPERATIONAL,"{'location': {'lat': 20.6387746, 'lng': -105.2...",https://maps.gstatic.com/mapfiles/place_api/ic...,Depa vallarta,NaN,NaN,ChIJGeUor59FIYQRJ4VgrqfrkuU,"{'compound_code': 'JQQF+GX Puerto Vallarta, Ja...",5.0,ChIJGeUor59FIYQRJ4VgrqfrkuU,...,NaN,+52 871 111 5995,Depa vallarta,5.0,"[{'author_name': 'Mr Vallarta', 'author_url': ...",1.0,NaN,[5],['Without fear of ... ... ... life'],NaN
20,OPERATIONAL,"{'location': {'lat': 20.6517281, 'lng': -105.2...",https://maps.gstatic.com/mapfiles/place_api/ic...,Hotel Maria Cristina,{'open_now': True},"[{'height': 4032, 'html_attributions': ['<a hr...",ChIJy_mBfnhPIYQRsV7_1gbsEKs,"{'compound_code': 'MQ2J+MW Puerto Vallarta, Ja...",3.7,ChIJy_mBfnhPIYQRsV7_1gbsEKs,...,NaN,+52 322 224 1882,Hotel Maria Cristina,3.7,"[{'author_name': 'Rocio Suárez Pérez', 'author...",53.0,https://www.facebook.com/hotelpitillal?fref=ts,"[5, 5, 3, 5, 4]",['Super central and inexpensive and everything...,NaN
21,OPERATIONAL,"{'location': {'lat': 20.6527274, 'lng': -105.2...",https://maps.gstatic.com/mapfiles/place_api/ic...,Fontanal Apartments Puerto Vallarta,NaN,"[{'height': 1536, 'html_attributions': ['<a hr...",ChIJAzrPL51GIYQRS9aDhqEoK5k,"{'compound_code': 'MQ3G+3M Puerto Vallarta, Ja...",4.4,ChIJAzrPL51GIYQRS9aDhqEoK5k,...,NaN,+52 322 182 0491,Fontanal Apartments Puerto Vallarta,4.4,"[{'author_name': 'Karsten Kramer', 'author_url...",78.0,https://fontanal-apartments-pv.negocio.site/,"[4, 4, 4, 5, 5]","['OK.', 'Excellent place very nice but the sec...",NaN
23,OPERATIONAL,"{'location': {'lat': 20.6520322, 'lng': -105.2...",https://maps.gstatic.com/mapfiles/place_api/ic...,Hotel MR,{'open_now': True},"[{'height': 3456, 'html_attributions': ['<a hr...",ChIJUzRV0j9PIYQRNelxpNI-Pa0,"{'compound_code': 'MQ2H+RG Puerto Vallarta, Ja...",3.9,ChIJUzRV0j9PIYQRNelxpNI-Pa0,...,NaN,+52 322 293 2182,Hotel MR,3.9,"[{'author_name': 'Ryan Warkentin', 'author_url...",85.0,NaN,"[5, 5, 5, 5, 4]",['A great hotel with even better prices. Off t...,NaN

In [29]:
df1 = df1.reset_index(drop=True)

,business_status,geometry,icon,name_x,opening_hours,photos,place_id,plus_code,rating_x,reference,...,price_level_x,international_phone_number,name_y,rating_y,reviews,user_ratings_total_y,website,all_ratings,all_reviews,price_level_y
0,OPERATIONAL,"{'location': {'lat': 20.6939009, 'lng': -105.2...",https://maps.gstatic.com/mapfiles/place_api/ic...,casa LAS PIÑAS,{'open_now': False},"[{'height': 640, 'html_attributions': ['<a hre...",ChIJIeVYvYNGIYQRh-9bPVK3fCU,"{'compound_code': 'MPVG+H8 Jarretaderas, Nayar...",4.6,ChIJIeVYvYNGIYQRh-9bPVK3fCU,...,NaN,+52 322 102 8516,casa LAS PIÑAS,4.6,"[{'author_name': 'Jovita Garcia Fernandez', 'a...",8.0,https://www.facebook.com/departamentos.laspinas/,"[5, 5, 5, 5, 5]","['An excellent place has all the comforts', 'I...",NaN
1,OPERATIONAL,"{'location': {'lat': 20.6920731, 'lng': -105.2...",https://maps.gstatic.com/mapfiles/place_api/ic...,Villas Victoria Confort Jarretaderas,{'open_now': True},NaN,ChIJdSKPg3xHIYQRlZ0pmfgVPiQ,"{'compound_code': 'MPRG+R4 Jarretaderas, Nayar...",5.0,ChIJdSKPg3xHIYQRlZ0pmfgVPiQ,...,NaN,+52 322 297 0093,Villas Victoria Confort Jarretaderas,5.0,"[{'author_name': 'anahi chavez', 'author_url':...",1.0,https://www.villasvictoriacomfort.com/,[5],"['It was more than I expected! Cheap, spacious...",NaN
2,OPERATIONAL,"{'location': {'lat': 20.6939068, 'lng': -105.2...",https://maps.gstatic.com/mapfiles/place_api/ic...,Hotel Posada Alejandra,NaN,"[{'height': 349, 'html_attributions': ['<a hre...",ChIJB2Yha4NGIYQRE-GTtF_VSAU,"{'compound_code': 'MPVF+HF Jarretaderas, Nayar...",4.0,ChIJB2Yha4NGIYQRE-GTtF_VSAU,...,NaN,+52 322 135 6145,Hotel Posada Alejandra,4.0,"[{'author_name': 'Juan Carlos Lopez', 'author_...",54.0,https://www.google.com/url?sa=t&source=web&rct...,"[3, 4, 3, 3, 5]","[""Just for one night it's alright"", 'Discreet'...",NaN
3,OPERATIONAL,"{'location': {'lat': 20.6241471, 'lng': -105.2...",https://maps.gstatic.com/mapfiles/place_api/ic...,Hotel Azul Romero,{'open_now': True},"[{'height': 3120, 'html_attributions': ['<a hr...",ChIJFW5JHF5FIYQRogsYTW-KvMI,"{'compound_code': 'JQFG+M7 Puerto Vallarta, Ja...",3.9,ChIJFW5JHF5FIYQRogsYTW-KvMI,...,NaN,+52 322 276 4854,Hotel Azul Romero,3.9,"[{'author_name': 'Al Reust', 'author_url': 'ht...",11.0,http://www.azulromero.com/,"[3, 4, 5, 4, 1]","['This is interesting, as it appears to be be ...",NaN
4,OPERATIONAL,"{'location': {'lat': 20.6225929, 'lng': -105.2...",https://maps.gstatic.com/mapfiles/place_api/ic...,Vacational Apartment Apartamento Vacacional De...,NaN,"[{'height': 1052, 'html_attributions': ['<a hr...",ChIJ9321RV5FIYQRwnf0qJkeIqU,"{'compound_code': 'JQFG+2M Puerto Vallarta, Ja...",4.8,ChIJ9321RV5FIYQRwnf0qJkeIqU,...,NaN,+52 322 270 9397,Vacational Apartment Apartamento Vacacional De...,4.8,"[{'author_name': 'Daniel Chilldres', 'author_u...",11.0,https://www.airbnb.mx/rooms/23351610,"[5, 4, 5, 5, 5]","['I loved it here!', 'The place is clean, plea...",NaN

In [31]:
df1['geometry'] = df1['geometry'].str.split(", 'v").str[0]

In [32]:
df1['geometry'] = df1['geometry'].str.split("location': ").str[1]

In [33]:
df1.iloc[0].geometry

"{'lat': 20.6939009, 'lng': -105.2742384}"

In [36]:
df1

,business_status,geometry,icon,name_x,opening_hours,photos,place_id,plus_code,rating_x,reference,...,price_level_x,international_phone_number,name_y,rating_y,reviews,user_ratings_total_y,website,all_ratings,all_reviews,price_level_y
0,OPERATIONAL,"{'lat': 20.6939009, 'lng': -105.2742384}",https://maps.gstatic.com/mapfiles/place_api/ic...,casa LAS PIÑAS,{'open_now': False},"[{'height': 640, 'html_attributions': ['<a hre...",ChIJIeVYvYNGIYQRh-9bPVK3fCU,"{'compound_code': 'MPVG+H8 Jarretaderas, Nayar...",4.6,ChIJIeVYvYNGIYQRh-9bPVK3fCU,...,NaN,+52 322 102 8516,casa LAS PIÑAS,4.6,"[{'author_name': 'Jovita Garcia Fernandez', 'a...",8.0,https://www.facebook.com/departamentos.laspinas/,"[5, 5, 5, 5, 5]","['An excellent place has all the comforts', 'I...",NaN
1,OPERATIONAL,"{'lat': 20.6920731, 'lng': -105.2747303}",https://maps.gstatic.com/mapfiles/place_api/ic...,Villas Victoria Confort Jarretaderas,{'open_now': True},NaN,ChIJdSKPg3xHIYQRlZ0pmfgVPiQ,"{'compound_code': 'MPRG+R4 Jarretaderas, Nayar...",5.0,ChIJdSKPg3xHIYQRlZ0pmfgVPiQ,...,NaN,+52 322 297 0093,Villas Victoria Confort Jarretaderas,5.0,"[{'author_name': 'anahi chavez', 'author_url':...",1.0,https://www.villasvictoriacomfort.com/,[5],"['It was more than I expected! Cheap, spacious...",NaN
2,OPERATIONAL,"{'lat': 20.6939068, 'lng': -105.2763239}",https://maps.gstatic.com/mapfiles/place_api/ic...,Hotel Posada Alejandra,NaN,"[{'height': 349, 'html_attributions': ['<a hre...",ChIJB2Yha4NGIYQRE-GTtF_VSAU,"{'compound_code': 'MPVF+HF Jarretaderas, Nayar...",4.0,ChIJB2Yha4NGIYQRE-GTtF_VSAU,...,NaN,+52 322 135 6145,Hotel Posada Alejandra,4.0,"[{'author_name': 'Juan Carlos Lopez', 'author_...",54.0,https://www.google.com/url?sa=t&source=web&rct...,"[3, 4, 3, 3, 5]","[""Just for one night it's alright"", 'Discreet'...",NaN
3,OPERATIONAL,"{'lat': 20.6241471, 'lng': -105.2243218}",https://maps.gstatic.com/mapfiles/place_api/ic...,Hotel Azul Romero,{'open_now': True},"[{'height': 3120, 'html_attributions': ['<a hr...",ChIJFW5JHF5FIYQRogsYTW-KvMI,"{'compound_code': 'JQFG+M7 Puerto Vallarta, Ja...",3.9,ChIJFW5JHF5FIYQRogsYTW-KvMI,...,NaN,+52 322 276 4854,Hotel Azul Romero,3.9,"[{'author_name': 'Al Reust', 'author_url': 'ht...",11.0,http://www.azulromero.com/,"[3, 4, 5, 4, 1]","['This is interesting, as it appears to be be ...",NaN
4,OPERATIONAL,"{'lat': 20.6225929, 'lng': -105.2232518}",https://maps.gstatic.com/mapfiles/place_api/ic...,Vacational Apartment Apartamento Vacacional De...,NaN,"[{'height': 1052, 'html_attributions': ['<a hr...",ChIJ9321RV5FIYQRwnf0qJkeIqU,"{'compound_code': 'JQFG+2M Puerto Vallarta, Ja...",4.8,ChIJ9321RV5FIYQRwnf0qJkeIqU,...,NaN,+52 322 270 9397,Vacational Apartment Apartamento Vacacional De...,4.8,"[{'author_name': 'Daniel Chilldres', 'author_u...",11.0,https://www.airbnb.mx/rooms/23351610,"[5, 4, 5, 5, 5]","['I loved it here!', 'The place is clean, plea...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
382,OPERATIONAL,"{'lat': 20.6769383, 'lng': -105.285772}",https://maps.gstatic.com/mapfiles/place_api/ic...,Grand Luxxe Punta Tower at Vidanta Nuevo Vallarta,{'open_now': True},"[{'height': 3480, 'html_attributions': ['<a hr...",ChIJ7zhNNCNEIYQRDyRrWYr8hLk,"{'compound_code': 'MPG7+QM Nuevo Vallarta, Nay...",4.9,ChIJ7zhNNCNEIYQRDyRrWYr8hLk,...,NaN,+52 322 226 4000,Grand Luxxe Punta Tower at Vidanta Nuevo Vallarta,4.9,"[{'author_name': 'John Bittle', 'author_url': ...",64.0,https://www.vidanta.com/en/web/nuevo-vallarta/...,"[5, 5, 5, 5, 5]",['Love this resort and hotel. Best room ever...,NaN
383,OPERATIONAL,"{'lat': 20.6837179, 'lng': -105.2898603}",https://maps.gstatic.com/mapfiles/place_api/ic...,R&A - Mayan Island,NaN,"[{'height': 4160, 'html_attributions': ['<a hr...",ChIJL33NqWNFIYQRe3bFJpXgzXw,"{'compound_code': 'MPM6+F3 Nuevo Vallarta, Nay...",5.0,ChIJL33NqWNFIYQRe3bFJpXgzXw,...,NaN,+1 619-346-1652,R&A - Mayan Island,5.0,"[{'author_name': 'alberto torreblanca', 'autho...",2.0,http://rabeachproperties.com/,[5],['Really nice view'],NaN
384,OPERATIONAL,"{'lat': 20.6843008, 'lng': -105.2780858}",https://maps.gstatic.com/mapfiles/place_api/ic...,Torre 6 The Grand Luxxe,NaN,"[{'height': 2992, 'html_attributions': ['<a hr...",ChIJo9we6EJFIYQRx9y4RoVO4Bs,"{'compound_code': 'MPMC+PQ Jarretaderas, Nayar...",4.6,ChIJo9we6EJFIYQRx9y4RoVO4Bs,...,NaN,NaN,Torre 6 The Grand Luxxe,4.6,"[{'author_name': 'Dana Nyborg', 'author_url': ...",15.0,NaN,"[4, 5, 3, 5, 5]","['New accommodations, but landscaping needs to...",NaN
385,OPERATIONAL,"{'lat': 20.684004, 'lng': -105.290116}",https://maps.gstatic.com/mapfiles/place_api/ic...,Condominios Mayan,NaN,NaN,ChIJLz-99m5FIYQRSFgBH-7v6ZI,"{'compound_code': 'MPM5+JX Nuevo Vallarta, Nay...",4.3,ChIJLz-99m5FIYQRSFgBH-7v6ZI,...,NaN,NaN,Condominios Mayan,4.3,"[{'author_name': 'EN LA BOCA DEL LOBO', 'autho...",3.0,NaN,"[3, 5, 5]","['Cool', '', '']",NaN
386,OPERATIONAL,"{'lat': 20.68943789999999, 'lng': -105.2845892}",https://maps.gstatic.com/mapfiles/place_api/ic...,Recolección Impex,NaN,NaN,ChIJH0EAEJ5GIYQRCI8cufdoQJ4,"{'compound_code': 'MPQ8+Q5 Jarretaderas, Nayar...",4.0,ChIJH0EAEJ5GIYQRCI8cufdoQJ4,...,NaN,NaN,Recolección Impex,4.0,"[{'author_name': 'Fabian Cibrian', 'author_url...",2.0,NaN,"[3, 5]","['There was no beef the day I went', '']",NaN

In [37]:
df_geo = df1['geometry'].map(eval).apply(pd.Series)

In [38]:
df_geo.head()

         lat         lng
0  20.693901 -105.274238
1  20.692073 -105.274730
2  20.693907 -105.276324
3  20.624147 -105.224322
4  20.622593 -105.223252

In [39]:
df1 = df1.merge(df_geo, how='outer', left_index=True, right_index=True)
df1.head()

,business_status,geometry,icon,name_x,opening_hours,photos,place_id,plus_code,rating_x,reference,...,name_y,rating_y,reviews,user_ratings_total_y,website,all_ratings,all_reviews,price_level_y,lat,lng
0,OPERATIONAL,"{'lat': 20.6939009, 'lng': -105.2742384}",https://maps.gstatic.com/mapfiles/place_api/ic...,casa LAS PIÑAS,{'open_now': False},"[{'height': 640, 'html_attributions': ['<a hre...",ChIJIeVYvYNGIYQRh-9bPVK3fCU,"{'compound_code': 'MPVG+H8 Jarretaderas, Nayar...",4.6,ChIJIeVYvYNGIYQRh-9bPVK3fCU,...,casa LAS PIÑAS,4.6,"[{'author_name': 'Jovita Garcia Fernandez', 'a...",8.0,https://www.facebook.com/departamentos.laspinas/,"[5, 5, 5, 5, 5]","['An excellent place has all the comforts', 'I...",NaN,20.693901,-105.274238
1,OPERATIONAL,"{'lat': 20.6920731, 'lng': -105.2747303}",https://maps.gstatic.com/mapfiles/place_api/ic...,Villas Victoria Confort Jarretaderas,{'open_now': True},NaN,ChIJdSKPg3xHIYQRlZ0pmfgVPiQ,"{'compound_code': 'MPRG+R4 Jarretaderas, Nayar...",5.0,ChIJdSKPg3xHIYQRlZ0pmfgVPiQ,...,Villas Victoria Confort Jarretaderas,5.0,"[{'author_name': 'anahi chavez', 'author_url':...",1.0,https://www.villasvictoriacomfort.com/,[5],"['It was more than I expected! Cheap, spacious...",NaN,20.692073,-105.274730
2,OPERATIONAL,"{'lat': 20.6939068, 'lng': -105.2763239}",https://maps.gstatic.com/mapfiles/place_api/ic...,Hotel Posada Alejandra,NaN,"[{'height': 349, 'html_attributions': ['<a hre...",ChIJB2Yha4NGIYQRE-GTtF_VSAU,"{'compound_code': 'MPVF+HF Jarretaderas, Nayar...",4.0,ChIJB2Yha4NGIYQRE-GTtF_VSAU,...,Hotel Posada Alejandra,4.0,"[{'author_name': 'Juan Carlos Lopez', 'author_...",54.0,https://www.google.com/url?sa=t&source=web&rct...,"[3, 4, 3, 3, 5]","[""Just for one night it's alright"", 'Discreet'...",NaN,20.693907,-105.276324
3,OPERATIONAL,"{'lat': 20.6241471, 'lng': -105.2243218}",https://maps.gstatic.com/mapfiles/place_api/ic...,Hotel Azul Romero,{'open_now': True},"[{'height': 3120, 'html_attributions': ['<a hr...",ChIJFW5JHF5FIYQRogsYTW-KvMI,"{'compound_code': 'JQFG+M7 Puerto Vallarta, Ja...",3.9,ChIJFW5JHF5FIYQRogsYTW-KvMI,...,Hotel Azul Romero,3.9,"[{'author_name': 'Al Reust', 'author_url': 'ht...",11.0,http://www.azulromero.com/,"[3, 4, 5, 4, 1]","['This is interesting, as it appears to be be ...",NaN,20.624147,-105.224322
4,OPERATIONAL,"{'lat': 20.6225929, 'lng': -105.2232518}",https://maps.gstatic.com/mapfiles/place_api/ic...,Vacational Apartment Apartamento Vacacional De...,NaN,"[{'height': 1052, 'html_attributions': ['<a hr...",ChIJ9321RV5FIYQRwnf0qJkeIqU,"{'compound_code': 'JQFG+2M Puerto Vallarta, Ja...",4.8,ChIJ9321RV5FIYQRwnf0qJkeIqU,...,Vacational Apartment Apartamento Vacacional De...,4.8,"[{'author_name': 'Daniel Chilldres', 'author_u...",11.0,https://www.airbnb.mx/rooms/23351610,"[5, 4, 5, 5, 5]","['I loved it here!', 'The place is clean, plea...",NaN,20.622593,-105.223252

In [40]:
df1.describe(include='all')

,business_status,geometry,icon,name_x,opening_hours,photos,place_id,plus_code,rating_x,reference,...,name_y,rating_y,reviews,user_ratings_total_y,website,all_ratings,all_reviews,price_level_y,lat,lng
count,387,387,387,387,183,361,387,386,387.000000,387,...,387,387.000000,387,387.000000,265,387,387,1.0,387.000000,387.000000
unique,1,384,4,383,2,361,387,372,NaN,387,...,383,NaN,387,NaN,259,204,387,NaN,NaN,NaN
top,OPERATIONAL,"{'lat': 20.65340699999999, 'lng': -105.2253316}",https://maps.gstatic.com/mapfiles/place_api/ic...,Casa Corazon,{'open_now': True},"[{'height': 766, 'html_attributions': ['<a hre...",ChIJH07bwLxFIYQRwnD_-wmnVPE,"{'compound_code': 'MQ3F+9V Puerto Vallarta, Ja...",NaN,ChIJH07bwLxFIYQRwnD_-wmnVPE,...,Casa Corazon,NaN,[{'author_name': 'Luis Alberto Morales Sanchez...,NaN,https://www.vidanta.com/web/nuevo-vallarta,"[5, 5, 5, 5, 5]","[""Should be zero stars if at all possible. Dur...",NaN,NaN,NaN
freq,387,3,364,2,140,1,1,4,NaN,1,...,2,NaN,1,NaN,3,68,1,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.425065,NaN,...,NaN,4.424031,NaN,368.801034,NaN,NaN,NaN,2.0,20.621220,-105.241150
std,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.501673,NaN,...,NaN,0.501207,NaN,859.683515,NaN,NaN,NaN,NaN,0.034350,0.016784
min,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,...,NaN,1.000000,NaN,1.000000,NaN,NaN,NaN,2.0,20.532667,-105.291951
25%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.200000,NaN,...,NaN,4.200000,NaN,7.000000,NaN,NaN,NaN,2.0,20.600570,-105.246316
50%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.500000,NaN,...,NaN,4.500000,NaN,33.000000,NaN,NaN,NaN,2.0,20.615105,-105.236038
75%,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4.800000,NaN,...,NaN,4.800000,NaN,190.000000,NaN,NaN,NaN,2.0,20.648100,-105.230990
max,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.000000,NaN,...,NaN,5.000000,NaN,6217.000000,NaN,NaN,NaN,2.0,20.693907,-105.214793

In [41]:
df1[df1['geometry']=="{'lat': 20.65340699999999, 'lng': -105.2253316}"]

,business_status,geometry,icon,name_x,opening_hours,photos,place_id,plus_code,rating_x,reference,...,name_y,rating_y,reviews,user_ratings_total_y,website,all_ratings,all_reviews,price_level_y,lat,lng
30,OPERATIONAL,"{'lat': 20.65340699999999, 'lng': -105.2253316}",https://maps.gstatic.com/mapfiles/place_api/ic...,Hard rock hotel,NaN,"[{'height': 3024, 'html_attributions': ['<a hr...",ChIJq0pp-CxFIYQRFGcrW0jD2YU,"{'compound_code': 'MQ3F+9V Puerto Vallarta, Ja...",3.8,ChIJq0pp-CxFIYQRFGcrW0jD2YU,...,Hard rock hotel,3.8,"[{'author_name': 'Lucho Gutierrez', 'author_ur...",4.0,NaN,"[5, 1, 5, 4]","['Love it, a friendly treatment by all the st...",NaN,20.653407,-105.225332
31,OPERATIONAL,"{'lat': 20.65340699999999, 'lng': -105.2253316}",https://maps.gstatic.com/mapfiles/place_api/ic...,Puerto Vallarta,NaN,"[{'height': 1280, 'html_attributions': ['<a hr...",ChIJJ7hW4RNFIYQReKCg-JvCd5w,"{'compound_code': 'MQ3F+9V Puerto Vallarta, Ja...",5.0,ChIJJ7hW4RNFIYQReKCg-JvCd5w,...,Puerto Vallarta,5.0,"[{'author_name': 'IXOTECUTLI ZIGEINER', 'autho...",1.0,NaN,[5],['Cool place PAL shitter'],NaN,20.653407,-105.225332
32,OPERATIONAL,"{'lat': 20.65340699999999, 'lng': -105.2253316}",https://maps.gstatic.com/mapfiles/place_api/ic...,Sunscape,NaN,NaN,ChIJVVVVVYFFIYQRdJ6i5dBNWPA,"{'compound_code': 'MQ3F+9V Puerto Vallarta, Ja...",3.7,ChIJVVVVVYFFIYQRdJ6i5dBNWPA,...,Sunscape,3.7,"[{'author_name': 'Alma Delia Chàvez Amezcua', ...",3.0,https://www.sunscaperesorts.mx/,"[5, 1, 5]","['Cool', ""I had a reservation and they wouldn'...",NaN,20.653407,-105.225332

In [65]:
df1.iloc[3].all_reviews

"['This is interesting, as it appears to be be under new ownership. It has a new paint job on the front, I have not taken time to speak with the new managers. In the past few years I know of people who have did extended vacations as the prices were reasonable. Access in the local community offers many things (I live across the street).  There is a Bus Route to Centro up the hill and return from Centro down the hill. They have a few rooms for Family or Long Term. I have seen Buses unload and many people take over the Hotel in the past. Time will tell.', 'Comfortable and decent, it is 10 minutes from the beach\\nThe water heater does not work and neither does the internet, but good for spending the night', 'Very good cows in Guadalajara', 'Very good', 'Change of administration and they did not make the deposit valid according to why the past administration did not give it to them 😒 I had no other choice than to stay there since according to what I had booked and I had about 50 people obviously I would not find a hotel elsewhere\\nWe did not pull the boiler, the minisplit, the wifi, they left only the maintenance man who could not cope with 10 rented rooms that all had problems and to finish there were lizards all over the hotel 😐 it is not close to the beach and The closest is private and not close to the main avenue, I just went on July 14 and what I am sure I will not return again, maybe it was my fault for wanting something cheaper\\nBetter for the other one even if it is something more expensive but worth it']"

In [45]:
df1.shape

(387, 26)

In [46]:
df1.to_csv(r'df1csv.csv', index=True, header=True, index_label=False)

In [69]:
import gensim